### ISSUE TITLE
Finalise Project Plan

### ISSUE THREAD

**Issue by DarkPurple141** [SmartCourse/app#30]
Project plan needs final work editing and agreement.

Once this issue is fully resolved the document should be entirely done.

Taken inspiration from: https://www.atlassian.com/agile/product-management/requirements

**Comment by DarkPurple141** [comment]
The following should be added to existing project plan:

1. [ ] Add Problem Hypothesis (sorta done)
2. [ ] Value (What drives value in product, problem solution)
3. [ ] Personas (Different types of users to keep in mind)
4. [ ] Stakeholders (People that will get value, or have stake in the process)
5. [ ] Define what an MVP looks like.

@PapaPwn
